Bump to allow for React 16, fix test
Automattic/interpolate-components pull request #12
Opened 2017-11-11 09:47 UTC by ockham

Broken out of #11.

To test:
* `rm -r node_modules/`
* `npm install`
* `grep version node_modules/react/package.json` (should return 16.something)
* `npm run test` should pass

2017-11-13 17:28 UTC, samouri commented
I followed the testing instructions and everything lgtm.
CircleCI is upset for reasons that I doubt are relevant to this PR:
```
Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.

Permission denied (publickey).

fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

git command i returned 128: 
```

2017-11-13 17:29 UTC, samouri approved these changes

2017-11-13 17:29 UTC, samouri requested changes
also need to update `package.json`!

2017-11-15 10:42 UTC, ockham commented
> also need to update `package.json`!

The package version you mean? Yeah, wasn't sure about immediately releasing vs trying to also get #11 in, but then again, let's not get blocked by that.

2017-11-15 10:49 UTC, merged